name: Record Android screenshot tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Choose branch to commit updated screenshots on'     
        required: true

jobs:
  record:
    runs-on: macos-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.event.inputs.branch }}

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      -  name: Record screenshots on Android emulator
         uses: ReactiveCircus/android-emulator-runner@v2.14.2
         with:
           api-level: 28
           target: default
           arch: x86
           profile: Nexus 6
           emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
           disable-animations: true
           script: ./gradlew executeScreenshotTests -Precord
           working-directory: ./android
 
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.8.0
        with:
          commit_message: Update Android test screenshots
          file_pattern: '*.png'
